Add private dns zone for platform.pagopa.it
pagopa/pagopa-infra pull request #116
Opened 2022-01-19 18:09 UTC by infantesimone

### List of changes

- Add private dns zone for `platform.pagopa.it` in order to allow the components in `vnet` and `vnet_integration` to resolve `api.platform.pagopa.it` with the apim ip.

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-01-19 18:16 UTC, pasqualedevita requested changes
Top @infantesimone only change resource name and other references

2022-01-19 18:16 UTC, pasqualedevita commented on src/dns_private.tf
> +resource "azurerm_private_dns_zone" "apim_private_dns_zone" {
Better call platform_private_dns_zone

2022-01-19 18:20 UTC, infantesimone commented on src/dns_private.tf
> +resource "azurerm_private_dns_zone" "apim_private_dns_zone" {
done

2022-01-20 07:48 UTC, pasqualespica approved these changes
🚀 great @infantesimone in this way all applications in to main `vnet` could call apim service directly 💪

2022-01-20 10:12 UTC, merged