[PAG-710] add apim
pagopa/pagopa-infra pull request #14
Opened 2021-09-22 07:13 UTC by pasqualespica

The purpose of this PR is to add APIM according to [Nuova architettura pagoPA](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/384141796/Nuova+architettura+pagoPA)
### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-09-22 10:40 UTC, pasqualedevita approved these changes
lgtm

2021-09-22 12:25 UTC, pasqualedevita requested changes

2021-09-22 12:25 UTC, pasqualedevita commented on src/env/prod/terraform.tfvars
> +apim_sku                       = "Premium_1"
```suggestion
apim_sku                       = "Developer_1" # change to Premium_1 before launch
```

2021-09-22 12:26 UTC, pasqualedevita requested changes

2021-09-22 12:26 UTC, pasqualedevita commented on src/env/uat/terraform.tfvars
> +cidr_subnet_redis     = ["10.1.132.0/24"]
please move under cidr_subnet_appgateway

2021-09-22 13:15 UTC, infantesimone commented on src/apim.tf
> +  api_domain        = var.env_short == "p" ? "api.platoform.pagopa.it" : format("api.%s.platoform.pagopa.it", lower(var.tags["Environment"]))
typo :-)

2021-09-22 17:04 UTC, pasqualedevita approved these changes
Is this pr applied?
If yes we can merge

2021-09-22 21:09 UTC, pasqualespica commented
> Is this pr applied?
> If yes we can merge

applied in `dev`

2021-09-23 11:12 UTC, pasqualedevita approved these changes

2021-09-23 11:12 UTC, merged