feat: Add GPD Upload service infra [PAGOPA-1360]
pagopa/pagopa-infra pull request #1532
Opened 2023-11-28 10:14 UTC by AngeloCaporaso

### List of changes

- Blob storage with SFTP enabled
- `STATUS` cosmos container 

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-01-08 10:38 UTC, AngeloCaporaso commented on src/domains/gps-common/03_cosmosdb.tf
> +module "gpd_cosmosdb_containers" {
duplicated

2024-01-08 10:43 UTC, AngeloCaporaso commented on src/domains/gps-common/03_gpd_storage_account.tf
> +      # match_blob_index_tag {
remove if useless

2024-01-09 11:15 UTC, diegolagospagopa requested changes

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/env/weu-prod/terraform.tfvars
> +gpd_account_replication_type                                       = "GZRS"
please change to `GRS`

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/env/weu-uat/terraform.tfvars
> +gpd_account_replication_type                                       = "ZRS"
Please change to GRS

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/99_variables.tf
> +  default     = ["10.1.152.16/29"]
Please don't use default values, but prefer to put into the variables files

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/03_gpd_storage_account.tf
> +  blob_versioning_enabled       = false
Please enable versioning for prod

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/03_gpd_storage_account.tf
> +module "gpd_sa" {
Please can you change the module name to gpd_sa_sftp?

2024-01-09 11:15 UTC, diegolagospagopa commented on src/domains/gps-common/03_gpd_storage_account.tf
> +  name                = replace("${local.project}-gpd-sa", "-", "")
please change the storage name to 

```suggestion
  name                = replace("${local.project}-gpd-sa-sftp", "-", "")
```

2024-01-15 16:04 UTC, pasqualespica requested changes

2024-01-15 16:04 UTC, pasqualespica commented on src/domains/gps-common/env/weu-prod/terraform.tfvars
> +gpd_sa_blob_versioning_enabled                                     = true
@AngeloCaporaso should be set to `false` for https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-known-issues

2024-01-26 16:11 UTC, pasqualespica approved these changes

2024-01-26 16:11 UTC, merged