Update nodo ws
pagopa/pagopa-infra pull request #172
Opened 2022-02-21 13:14 UTC by infantesimone

### List of changes

- add the following `nodo` ws:
  - `nodoChiediInformativaPA`
  - `nodoChiediTemplateInformativaPSP`
  - `nodoVerificaRPT`
  - `nodoAttivaRPT`
  - `nodoInviaRT`
  - `nodoInviaFlussoRendicontazione`
  - `nodoChiediCatalogoServizi`
  - `nodoChiediNumeroAvviso`

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-02-21 14:44 UTC, uolter approved these changes

2022-02-21 16:14 UTC, pasqualespica requested changes
@infantesimone could u  add `nodoChiediElencoQuadraturePSP` too ? 

@corvettafabio i updated [docs](https://docs.google.com/spreadsheets/d/1n34d5Cpo2mvZ7xdhvvC-xZQvgY7bVosGVE5u0YIRz_k/edit#gid=72242577) according to request change.

2022-02-21 16:42 UTC, infantesimone commented
> nodoChiediElencoQuadraturePSP



> @infantesimone could u add `nodoChiediElencoQuadraturePSP` too ?
> 
> @corvettafabio i updated [docs](https://docs.google.com/spreadsheets/d/1n34d5Cpo2mvZ7xdhvvC-xZQvgY7bVosGVE5u0YIRz_k/edit#gid=72242577) according to request change.

done

2022-02-21 16:42 UTC, infantesimone commented
> nodoChiediElencoQuadraturePSP



> @infantesimone could u add `nodoChiediElencoQuadraturePSP` too ?
> 
> @corvettafabio i updated [docs](https://docs.google.com/spreadsheets/d/1n34d5Cpo2mvZ7xdhvvC-xZQvgY7bVosGVE5u0YIRz_k/edit#gid=72242577) according to request change.

done

2022-02-24 14:39 UTC, pasqualespica approved these changes

2022-02-24 16:58 UTC, uolter approved these changes

2022-02-24 17:05 UTC, merged