chore: adding columns to config db PAGOPA-1732
pagopa/pagopa-infra pull request #2284
Opened 2024-07-11 14:26 UTC by FedericoRuzzier

### List of changes
Adding `no_aca` and `no_standin` columns in `pa_stazione_pa` table inside config db

### Motivation and context
Change needed to align the db with the latest api-config improvements

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-07-11 14:27 UTC, FedericoRuzzier commented
All the schemas in: 
- cfg-partner
- offline
- online
- re
- wfesp

2024-07-12 08:10 UTC, cristianosticca-pagopa requested changes
@FedericoRuzzier mea culpa sul task non preciso ... i nuovi attributi dovrebbero essere chiamati "ACA" e STANDIN" (senza mettere il "NO_" davanti). Perchè altrimenti dovremmo gestire logiche di doppia negazione e potremmo avere ambiguità / confusione. Quindi se l'EC dichiara di non poter inviare le PD in ACA metterà "no" sul Backoffice e il flag verrà valorizzato con "N". 

Scusami di nuovo.

2024-07-15 07:24 UTC, jacopocarlini commented on src/psql/nodo/liquibase/changelog/cfg/3.30.0/db.changelog-20240711000000_add_field_no_aca.xml
> +            <column name="no_aca" type="CHAR(1)"/>
```suggestion
            <column name="aca" type="CHAR(1)"/>
```

2024-07-15 07:24 UTC, jacopocarlini commented on src/psql/nodo/liquibase/changelog/cfg/3.30.0/db.changelog-20240711000001_add_field_no_standin.xml
> +            <column name="no_standin" type="CHAR(1)"/>
```suggestion
            <column name="tandin" type="CHAR(1)"/>
```

2024-07-15 07:25 UTC, jacopocarlini commented on src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.30.0.xml
> +  <include file="./${version}/db.changelog-20240711000000_add_field_no_aca.xml" labels="${version}"/>
```suggestion
  <include file="./${version}/db.changelog-20240711000000_add_field_aca.xml" labels="${version}"/>
```

2024-08-08 09:32 UTC, cristianosticca-pagopa approved these changes
LGM

2024-08-08 09:33 UTC, jacopocarlini approved these changes

2024-08-08 09:33 UTC, merged