[PPANTT-115] feat: Introduced payment-options infra
pagopa/pagopa-infra pull request #2405
Opened 2024-09-09 08:02 UTC by alessio-cialini

### List of changes

- Introducing payment-options infra domain

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-09-18 08:39 UTC, jacopocarlini requested changes
@alessio-cialini can you apply in DEV?

PS: see the comments

2024-09-18 08:39 UTC, jacopocarlini commented on src/domains/paymentoptions-secrets/99_locals.tf
> +  monitor_action_group_email_name = "PagoPA"
```suggestion
```
remove these lines. They aren't used.

2024-09-18 08:39 UTC, jacopocarlini commented on src/domains/paymentoptions-common/10_github_identity.tf
> +    "pagopa-template-notice-pdf"
please put the right repo names

2024-09-18 08:49 UTC, jacopocarlini requested changes

2024-09-18 08:49 UTC, jacopocarlini commented on src/domains/paymentoptions-app/04_apim_notice_generator.tf
rename this file please

2024-09-18 08:49 UTC, jacopocarlini commented on src/domains/paymentoptions-app/04_apim_notice_generator.tf
> +  product_id   = "pagopa_notices_generator"
👀 change this id

2024-09-23 14:41 UTC, jacopocarlini approved these changes

2024-09-25 08:48 UTC, pasqualespica approved these changes

2024-09-25 08:49 UTC, merged