feat: new product gpd_for_aca PAGOPA-2195
pagopa/pagopa-infra pull request #2501
Opened 2024-10-21 15:20 UTC by FedericoRuzzier

### List of changes
New product gpd_for_aca with aca apis

### Motivation and context
Needed in order to extract subscription keys

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-11-18 08:56 UTC, aomegax requested changes

2024-11-18 08:56 UTC, aomegax commented on src/domains/aca-app/api/gpd-for-aca-services/v1/_base_policy.xml
> +      <when condition="@(Regex.IsMatch(context.Request.Url.Path, @"^\/pagopa-gpd-core\/organizations\/([a-zA-Z0-9]{11})\/debtpositions$", RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(500)) && (
move from all-api to single api (for example https://github.com/pagopa/pagopa-infra/blob/f6d39b2a9e336725cf871a43f6a9371b50e82463/src/core/apim_payment_manager.tf#L930)

2024-11-18 08:56 UTC, aomegax commented on src/domains/aca-app/api/gpd-for-aca-services/v1/_base_policy.xml
> +        <!-- ################################################################### -->
This is common to GPD, please create a fragment generalizing code

2024-11-18 08:56 UTC, aomegax commented on src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
> +      <when condition="@(Regex.IsMatch(context.Request.Url.Path, @"^\/pagopa-gpd-core\/organizations\/([a-zA-Z0-9]{11})\/debtpositions$", RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(500)) && (
as before, add to the specific api

2024-11-18 08:56 UTC, aomegax commented on src/domains/gps-app/api/gpd_api/debt-position-services/v2/_base_policy.xml
> +      <when condition="@(Regex.IsMatch(context.Request.Url.Path, @"^\/pagopa-gpd-core\/organizations\/([a-zA-Z0-9]{11})\/debtpositions$", RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(500)) && (
as said before.
perhaps you can create a fragment too, where the input params are path and serviceType values

2024-11-19 16:54 UTC, FedericoRuzzier commented on src/domains/gps-app/99_variables.tf
> +variable "service_type_gpd" {
Delete

2024-11-19 16:54 UTC, FedericoRuzzier commented on src/domains/aca-app/99_variables.tf
> +variable "service_type_aca" {
Delete

2024-11-25 14:50 UTC, merged