[PPR-356] Infra for Advanced Fees Management PoC
pagopa/pagopa-infra pull request #284
Opened 2022-06-08 07:46 UTC by aomegax

This PR is for creating a base infrastructure for the PoC regarding marketplace for advanced fees management (for more info 👉 [here](https://pagopa.atlassian.net/wiki/spaces/PPR/pages/511443239/GEC+-+Design+Review+-+Marketplace)). 

At the moment, the needs are:
- an app service to deploy java+spring applicative
- a cosmosdb to store data

The infra should be created only in dev env and, in the next future, it will be revised to adopt AKS.

### List of changes

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-06-08 08:37 UTC, pasqualespica requested changes

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +  count                                          = var.advanced_fees_management_enabled && var.cidr_subnet_advanced_fees_management != null ? 1 : 0
I'd be more explicit I'd test env variable directly. It's a PoC

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +module "advanced_fees_management_app_service" {
ok , but DR mention AKS

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +    COSMOS_KEY2 = data.azurerm_key_vault_secret.afm_cosmos_key2.value
key2 too ?

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +  always_on           = false
evaluate if it's better set this one to `true` in dev too

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +  name     = format("%s-afm-cosmos", local.project)
rename with `-<YOUR_NAME>-cosmos-account`

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +  is_virtual_network_filter_enabled = false
it is preferable set to `true` and then add to `allowed_virtual_network_subnet_ids` whoever the access permissions

2022-06-08 08:37 UTC, pasqualespica commented on src/api/afm_api/marketplace/v1/_base_policy.xml.tpl
> +    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.
you need this policy for the this PoC ?

2022-06-08 08:37 UTC, pasqualespica commented on src/advanced_fees_management.tf
> +}
no `cosmosdb_sql_container` ? db only ?

2022-06-08 08:51 UTC, aomegax commented on src/advanced_fees_management.tf
> +module "advanced_fees_management_app_service" {
yes, but there is a note that specifies we will use app service for time constraints (we have less than 10 days).
AKS will be the solution for the next future.

2022-06-08 08:58 UTC, aomegax commented on src/api/afm_api/marketplace/v1/_base_policy.xml.tpl
> +    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.
no, it is a wrong cut&paste 👍

2022-06-08 09:09 UTC, aomegax commented on src/advanced_fees_management.tf
> +}
yes, wip 🚧

2022-06-09 13:40 UTC, aomegax commented on src/advanced_fees_management.tf
> +  count                                          = var.advanced_fees_management_enabled && var.cidr_subnet_advanced_fees_management != null ? 1 : 0
done

2022-06-09 13:40 UTC, aomegax commented on src/advanced_fees_management.tf
> +    COSMOS_KEY2 = data.azurerm_key_vault_secret.afm_cosmos_key2.value
done

2022-06-10 14:56 UTC, pasqualespica approved these changes
great 👍

2022-06-11 14:07 UTC, merged