feat: adding apim for pagopa-selfcare api
pagopa/pagopa-infra pull request #430
Opened 2022-09-29 15:06 UTC by andrea-putzu

### List of changes

Adding APIM for Selfcare pagoPA product Backend

### Motivation and context

### Type of changes

- [X] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [] Yes, users may be impacted applying this change
- [X] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [] Yes
- [X] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-09-29 15:15 UTC, pasqualespica requested changes

2022-10-10 10:11 UTC, diegolagospagopa requested changes

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/04_apim_selc.tf
> +  name                  = format("%s-pagopa-selc-api", local.project)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/04_apim_selc.tf
> +  name                = format("%s-pagopa-selc-api", var.env_short)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +  name     = format("%s-selc-fe-rg", local.project)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +      name  = replace(format("SPA-%s", spa), "-", "")
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +          match_values     = [format("/%s/", spa)]
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +        destination             = format("/%s/index.html", spa)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +  hostname              = format("%s.%s.%s", local.dns_zone_selc, local.dns_zone_platform, local.external_domain)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/06_selfcare-fe.tf
> +  dns_zone_name                = format("%s.%s", local.dns_zone_platform, local.external_domain)
please use interpolation

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/99_variables.tf
> +  type = string
please add description and validation constraint, as in other projects

2022-10-10 10:11 UTC, diegolagospagopa commented on src/domains/selc-app/api/pagopa_token_exchange/jwt_exchange.xml.tpl
> +                <audience>api.platform.pagopa.it</audience>
can be parametrized?

2022-10-10 20:31 UTC, pasqualespica approved these changes

2022-10-10 20:32 UTC, merged