Update app gtw configs
pagopa/pagopa-infra pull request #554
Opened 2022-11-24 15:58 UTC by infantesimone

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-11-24 16:21 UTC, pasqualedevita requested changes
add also Softlab L1 Pagamenti VPN ips for web-bo
I don't know if is required also  NEXI VPN for web-bo

2022-11-24 17:09 UTC, infantesimone commented
> add also Softlab L1 Pagamenti VPN ips for web-bo I don't know if is required also NEXI VPN for web-bo

@pasqualedevita done

2022-11-25 13:35 UTC, infantesimone commented
@pasqualespica @pasqualedevita can you give me feedback on the latest configurations to enable nexi vpn for admin-panel and web-bo?

2022-11-29 16:13 UTC, pasqualedevita submitted a review, later dismissed

2022-12-01 07:37 UTC, merged